name = "One day hope"
author = "Arix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71b78a44bd196fdedc9520228a1d0068771ac7ccf3eb1ea12cb5235387014cdd"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
