name = "One day hope"
author = "Arix"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f6d7bc7d398629eb040c0730a56cb2a84bd3a081f2668152edd92242644095b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
