mode = "off"
chunk_rebuild_scheduler = "culling"

[light_sources]
	water_sensitive_check = true
	beam = true
	block_entities = false
	firefly = true
	glowing_effect = true
	entities = true
	self = true
	tnt = "simple"
	sonic_boom = true
	creeper = "simple"
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				pale_oak_boat = true
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				jungle_chest_boat = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				happy_ghast = true
				drowned = true
				creaking = true
				item = true
				oak_chest_boat = true
				goat = true
				horse = true
				vindicator = true
				birch_boat = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				oak_boat = true
				glow_item_frame = true
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				dark_oak_chest_boat = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				cherry_chest_boat = true
				acacia_chest_boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				mannequin = true
				lingering_potion = true
				cow = true
				birch_chest_boat = true
				magma_cube = true
				pig = true
				skeleton = true
				spruce_boat = true
				frog = true
				hoglin = true
				armadillo = true
				splash_potion = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				jungle_boat = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				acacia_boat = true
				furnace_minecart = true
				pale_oak_chest_boat = true
				mangrove_boat = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				shulker_bullet = true
				squid = true
				enderman = true
				dragon_fireball = true
				copper_golem = true
				chicken = true
				sniffer = true
				dark_oak_boat = true
				trader_llama = true
				donkey = true
				bamboo_chest_raft = true
				bogged = true
				bamboo_raft = true
				fox = true
				mangrove_chest_boat = true
				cherry_boat = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true
				spruce_chest_boat = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.livingthings]
				shark = true
				mantaray = true
				snail = true
				thrown_ostrich_egg = true
				monkey = true
				koala = true
				ostrich = true
				owl = true
				ancient_blaze = true
				baby_ender_dragon = true
				shroomie = true
				lion = true
				flamingo = true
				nether_knight = true
				raccoon = true
				giraffe = true
				peacock = true
				elephant = true
				crab = true
				penguin = true
				seahorse = true

			[light_sources.settings.entities.mcwfurnitures]
				chair = true
				couch = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	background_sleep = true
